{
  "type": "record",
  "name": "MachineControlRules",
  "namespace": "local.home.arpa.control",
  "fields": [
    { "name": "version", "type": "string" },
    { "name": "machine_type", "type": "string" },
    { "name": "max_vibration", "type": "double" },
    { "name": "min_vibration", "type": "double" },
    { "name": "max_temperature", "type": "double" },
    { "name": "min_temperature", "type": "double" },
    { "name": "max_pressure", "type": "double" },
    { "name": "min_pressure", "type": "double" },
    { "name": "rule_profile", "type": "string" }
  ]
}
